// utils.ts
export function cleanAndTruncateDiff(rawDiff: string): string {
    const MAX_CHARS = 12000; // Roughly ~3,000 tokens. Perfectly safe for most LLMs.
    let cleanedLines: string[] = [];
    let skipCurrentFile = false;

    const lines = rawDiff.split('\n');

    for (const line of lines) {
        // Detect when the diff starts looking at a new file
        if (line.startsWith('diff --git')) {
            // If it's a massive autogenerated file or an image, ignore it entirely!
            if (line.includes('package-lock.json') || line.includes('yarn.lock') || line.endsWith('.svg')) {
                skipCurrentFile = true;
                cleanedLines.push(`\n--- [IGNORED AUTOGENERATED FILE] ---`);
            } else {
                skipCurrentFile = false;
            }
        }

        if (!skipCurrentFile) {
            cleanedLines.push(line);
        }
    }

    let finalDiff = cleanedLines.join('\n');

    // The Iron Gate for the AI Context Window
    if (finalDiff.length > MAX_CHARS) {
        console.log(`⚠️ Diff too large (${finalDiff.length} chars). Truncating to protect AI Context Window...`);
        finalDiff = finalDiff.substring(0, MAX_CHARS) + "\n\n... [REMAINDER OF DIFF TRUNCATED FOR AI SAFETY]";
    }

    return finalDiff;
}